apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-web-app-deployment
  labels:
    app: mongo-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-web-app
  template:
    metadata:
      name: mongo-web-app
      labels:
        app: mongo-web-app
    spec:
      containers:
        - name: mongo-web-app
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-pass
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-web-app-service
  labels:
    app: mongo-web-app
spec:
    selector:
        app: mongo-web-app
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # must be between 30000-32767
      nodePort: 30007
    type: NodePort