apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-app-deployment
spec:
  selector:
    matchLabels:
      app: autoscaling-app
  replicas: 1
  template:
    metadata:
      labels:
        app: autoscaling-app
    spec:
      containers:
        - name: autoscaling-app
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: SB_CONNECTION_STRING
              value: ${SB_CONNECTION_STRING_VALUE}
          
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          