apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-to-scale-deployment
spec:
  selector:
    matchLabels:
      app: app-to-scale
  replicas: 1
  template:
    metadata:
      labels:
        app: app-to-scale
    spec:
      containers:
        - name: app-to-scale
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80