apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-to-scale-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-to-scale-deployment
  minReplicaCount: 1 # should match with the number of replicas in the deployment
  maxReplicaCount: 15
  pollingInterval: 120               # Poll every 120 seconds
  cooldownPeriod: 300               # Wait 5 minutes before scaling down
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "30 7 * * *"            # Every day at 7:30 AM
        end: "29 15 * * *"             # scale-up until 15:29 PM
        desiredReplicas: "10"

    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "30 15 * * *"           # Every day at 15:30 PM
        desiredReplicas: "1"           # Ensure at least 1 replica during this period

    - type: resource
      metadata:
        name: cpu
        targetType: Utilization
        targetValue: "95"           # If resource exceeds  90% CPU utilization scale up